name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  packages: read
  contents: read
  security-events: write
  pull-requests: write
  checks: write

jobs:
  codeql:
    name: CodeQL - ${{ matrix.language }}
    uses: DWSR/actions/.github/workflows/codeql.yml@main
    strategy:
      matrix:
        include:
          - language: actions
            build-mode: none
    with:
      language: "${{ matrix.language }}"
      build-mode: "${{ matrix.build-mode }}"

  autoapprove-dependabot:
    name: Auto-approve Dependabot PRs
    uses: DWSR/actions/.github/workflows/autoapprove-dependabot.yml@main

  autoapprove-infra-bot:
    name: Auto-approve Infra Bot PRs
    uses: DWSR/actions/.github/workflows/autoapprove-infra-bot.yml@main

  check-actors:
    name: Check Authorized Actors
    uses: DWSR/actions/.github/workflows/authorized-actors.yml@main
